version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 211327774117.dkr.ecr.ap-northeast-2.amazonaws.com
      - REPOSITORY_URI_EUREKA=211327774117.dkr.ecr.ap-northeast-2.amazonaws.com/scott-commerce-eureka
      - REPOSITORY_URI_ACCOUNT=211327774117.dkr.ecr.ap-northeast-2.amazonaws.com/scott-commerce-account
      - REPOSITORY_URI_ORDER=211327774117.dkr.ecr.ap-northeast-2.amazonaws.com/scott-commerce-order
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...

      - cd eureka
      - chmod u+x gradlew
      - ./gradlew clean build
      - docker build --platform linux/amd64 -t $REPOSITORY_URI_EUREKA:latest .
      - docker tag $REPOSITORY_URI_EUREKA:latest $REPOSITORY_URI_EUREKA:$IMAGE_TAG

      - cd ../account-api
      - chmod u+x gradlew
      - ./gradlew clean build
      - docker build --platform linux/amd64 -t $REPOSITORY_URI_ACCOUNT:latest .
      - docker tag $REPOSITORY_URI_ACCOUNT:latest $REPOSITORY_URI_ACCOUNT:$IMAGE_TAG

      - cd ../order-api
      - chmod u+x gradlew
      - ./gradlew clean build
      - docker build --platform linux/amd64 -t $REPOSITORY_URI_ORDER:latest .
      - docker tag $REPOSITORY_URI_ORDER:latest $REPOSITORY_URI_ORDER:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...

      - docker push $REPOSITORY_URI_EUREKA:latest
      - docker push $REPOSITORY_URI_EUREKA:$IMAGE_TAG

      - docker push $REPOSITORY_URI_ACCOUNT:latest
      - docker push $REPOSITORY_URI_ACCOUNT:$IMAGE_TAG

      - docker push $REPOSITORY_URI_ORDER:latest
      - docker push $REPOSITORY_URI_ORDER:$IMAGE_TAG

      - echo Writing image definitions file...
      - printf '[{"name":"eureka", "imageUri":"%s"}, {"name":"account","imageUri":"%s"}, {"name":"order","imageUri":"%s"}]' $REPOSITORY_URI_EUREKA:$IMAGE_TAG $REPOSITORY_URI_ACCOUNT:$IMAGE_TAG $REPOSITORY_URI_ORDER:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - 'image*.json'
    - 'appspec.yaml'
    - 'taskdef.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imagedefinitions.json
