version: "3.8"
services:
  eureka-service:
    build:
      context: ./eureka
      dockerfile: Dockerfile_local
    ports:
      - "8761:8761"
  db:
    image: mysql:latest
    container_name: mysql-zerobase
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zeroorder
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
  account-api:
    build:
      context: ./account-api
      dockerfile: Dockerfile_local
    ports:
        - "8080:8080"
    restart: on-failure
    depends_on:
      - eureka-service
      - db
  order-api:
    build:
      context: ./order-api
      dockerfile: Dockerfile_local
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - eureka-service
      - db
