FROM openjdk:17-slim
COPY build/libs/account-api.jar account-api.jar
ENTRYPOINT ["java","-DSpring.profiles.active=compose","-jar","account-api.jar"]

#FROM openjdk:17-slim AS build
#WORKDIR /account-api
#COPY . .
#RUN chmod +x ./gradlew
#RUN ./gradlew build -x test

#FROM openjdk:17-slim
#WORKDIR /account-api
#COPY /account-api/build/libs/account-api.jar account-api.jar
#ENTRYPOINT ["java","-DSpring.profiles.active=default","-jar","account-api.jar"]