spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${cloud.db.url}
    driver-class-name: ${cloud.db.driver}
    username: ${cloud.db.id}
    password: ${cloud.db.pw}
  jwt:
    secret: ${cloud.jwt.secret}
  mail:
    host: ${cloud.google.mail.host}
    port: ${cloud.google.mail.port}
    username: ${cloud.google.mail.id}
    password: ${cloud.google.mail.pw}
eureka:
  client:
    service-url:
      defaultZone: ${cloud.eureka.url}



