spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${db.url}
    driver-class-name: ${db.driver}
    username: ${db.id}
    password: ${db.pw}
eureka:
  client:
    service-url:
      defaultZone: ${eureka.url}
