spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${aws.db.url}
    driver-class-name: ${aws.db.driver}
    username: ${aws.db.id}
    password: ${aws.db.pw}
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
