config:
  type: aws-parameterstore:/config/

spring:
  config:
    activate:
      on-profile: prod
    import: ${config.type}
  datasource:
    url: ${cloud.db.url}
    driver-class-name: ${cloud.db.driver}
    username: ${cloud.db.id}
    password: ${cloud.db.pw}
  jwt:
    secret: ${cloud.jwt.secret}
  mail:
    host: ${cloud.google.mail.host}
    port: ${cloud.google.mail.port}
    username: ${cloud.google.mail.id}
    password: ${cloud.google.mail.pw}
eureka:
  client:
    service-url:
      defaultZone: ${cloud.eureka.url}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    urls[0]:
      name: account-api
      url: ${cloud.account-api.doc}
#    urls[1]:
#      name: order-api
#      url: http://localhost:8081/api-docs
#    urls[2]:
#      name: chat-api
#      url: http://localhost:8085/api-docs
#    urls[3]:
#      name: test-api
#      url: http://localhost:8086/api-docs


