spring:
  config:
    activate:
      on-profile: compose
  datasource:
    url: jdbc:mysql://db:3306/ecommerce?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: 1234
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
email:
  server: http://43.202.0.217::8080

springdoc:
  swagger-ui:
    urls[0]:
      name: account-api
      url: http://43.202.0.217::8080/api-docs
    urls[1]:
      name: order-api
      url: http://43.202.0.217:8081/api-docs
    urls[2]:
      name: chat-api

