server:
  port: 8080
spring:
  application:
    name: account-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: ${google.mail.host}
    port: ${google.mail.port}
    username: ${google.mail.id}
    password: ${google.mail.pw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${local.db.url}
    driver-class-name: ${local.db.driver}
    username: ${local.db.id}
    password: ${local.db.pw}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

feign:
  okhttp:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
grpc:
  server:
    port: 6565
---
server:
  port: 8080
spring:
  application:
    name: account-api
  config:
    activate:
      on-profile: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: ${google.mail.host}
    port: ${google.mail.port}
    username: ${google.mail.id}
    password: ${google.mail.pw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${aws.db.url}
    driver-class-name: ${aws.db.driver}
    username: ${aws.db.id}
    password: ${aws.db.pw}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    defer-datasource-initialization: true

feign:
  okhttp:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.1.1.20:8761/eureka/
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: docker
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ddavvidsung@gmail.com
    password: hxxb awre djut qpuj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${docker.db.url}
    driver-class-name: ${docker.db.driver}
    username: ${docker.db.id}
    password: ${docker.db.pw}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
feign:
  okhttp:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
