spring:
  config:
    activate:
      on-profile: compose
  datasource:
    url: jdbc:mysql://db:3306/zeroorder?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka