spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${db_url}
    driver-class-name: ${db_driver}
    username: ${db_id}
    password: ${db_pw}
eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}
