server:
  port: 8081
spring:
  application:
    name: order-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: ${google_mail_host}
    port: ${google_mail_port}
    username: ${google_mail_id}
    password: ${google_mail_pw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${local.db.url}
    driver-class-name: ${local.db.driver}
    username: ${local.db.id}
    password: ${local.db.pw}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

feign:
  okhttp:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
#grpc:
#  client:
#    user-service:
#      address: static://localhost:6565
#      negotiation-type: plaintext
